# Generated by Django 5.1.1 on 2024-09-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_media_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataitem',
            old_name='placsemap',
            new_name='place_map',
        ),
    ]
