# Generated by Django 5.0.2 on 2024-09-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_dataitem_img_alter_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='webshop/static/imageDataItem/%y/%m/%d'),
        ),
        migrations.CreateModel(
            name='DataItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='pages.dataitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_items', to='pages.tag')),
            ],
        ),
    ]
