# Generated by Django 5.0.2 on 2024-09-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_tag_alter_dataitem_img_dataitemtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataItemTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
