# Generated by Django 5.0.2 on 2024-09-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_delete_dataitemtag_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/imageDataItem/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='place_map_1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='place_map_2',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='static/media/%Y/%m/%d'),
        ),
    ]
