# Generated by Django 5.0.2 on 2024-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_type_of_home_alter_dataitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_of_home',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
