# Generated by Django 5.1.1 on 2024-09-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_placsemap_dataitem_place_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='place_map',
        ),
        migrations.AddField(
            model_name='dataitem',
            name='place_map_1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='place_map_2',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
