# Generated by Django 5.0.2 on 2024-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_dataitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
