# Generated by Django 5.0.2 on 2024-09-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_dataitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='../webshop/static/DataItem/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='../webshop/static/media/%y/%m/%d'),
        ),
    ]
