# Generated by Django 5.0.2 on 2024-09-30 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_dataitem_img_alter_dataitem_place_map_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.type_of_home'),
        ),
    ]
